### PR TITLE
fixed broken logo image and profile image

### PR DESCRIPTION
**Pull request by rcode321**
Fixed the logo image and profile image.

### CODE REVIEW

**Comment by BennyCarlsson** [comment]
Great however it seems like you used an auto formatter and that usually ends up with bad merge conflicts :)

**Comment by rcode321** [comment]
Hi Benny how to resolve merge conflicts? i'm new with github, but i'll try to research it first how to resolve it tnx.

**Comment by BennyCarlsson** [comment]
Hi @rcode321 don't worry we all been new to something :)
here is a video from last year on how to solve a merge conflict https://www.youtube.com/watch?v=zOx5PJTY8CI

You can also make a completely new pull request if that is easier :)

**Comment by rcode321** [comment]
Hi Benny Thanks for the feedback, the video is really helpful. and I tried to fix the merge conflicts hope it's fixed.

**Comment by BennyCarlsson** [comment]
Great work! 👍

**Pull request merged**
