### PR TITLE
Added Brainy Favicon

### PR DESCRIPTION
**Pull request by Chizzoz**
- Edited index.html header section to reference icons
- copied icons to project root folder

### CODE REVIEW

**Comment by BennyCarlsson** [comment]
oh shoot someone already added a favicon if you think yours is better feel free to solve the merge conflict and I well merge it ;)

**Comment by Chizzoz** [comment]
Hehe! Beat me to it... Let me see if I can resolve.

**Comment by Chizzoz** [comment]
I believe the merge conflict has now been resolved. Kindly check!

**Comment by BennyCarlsson** [comment]
Looks good however it looks like you used auto formating on index.html and that will cause a lot of merge conflict in the future :)

**Comment by Chizzoz** [comment]
> Looks good however it looks like you used auto formating on index.html and that will cause a lot of merge conflict in the future :)

Really! Maybe VSCode was doing things in the background, let me merge current changes and try use Notepad++ instead

**Comment by Chizzoz** [comment]
Resolved conflicts and made a small change on the Hometown value

**Comment by BennyCarlsson** [comment]
Great 👍 merging

**Pull request merged**
