### PR TITLE
cleaned up html structure and clarified experience section

### PR DESCRIPTION
**Pull request by sparsell**
Organized an HTML file section (list of technologies and development methodologies)

### CODE REVIEW

**Comment by sparsell** [comment]
Let me know if I wasn't successful at resolving my merge conflict.  This has been excellent practice! Thank you for the opportunity.

**Comment by BennyCarlsson** [comment]
Hi, looks like there's still conflict that might however be because I merged some other pull requests before this one :)

**Comment by sparsell** [comment]
OK - trying again.  Thanks!

**Comment by BennyCarlsson** [comment]
Nice! Great work 👍

**Pull request merged**
