### PR TITLE
added an easter egg --> shows up when user types the words 'easter eg…

### PR DESCRIPTION
**Pull request by SidneyMachara**
added an easter egg --> shows up when user types the words 'easter eg…

### CODE REVIEW

**Comment by BennyCarlsson** [comment]
Looks great however there seems to be some merge conflicts probably because I merged some pull requests before this one. If you have time to fix it or make a new pull requests I'll happily merge it :)

**Comment by SidneyMachara** [comment]
fixed merge the  conflicts  :)

**Comment by SidneyMachara** [comment]
updated again :)

**Comment by BennyCarlsson** [comment]
Great 👍 merging

**Pull request merged**
