### PR TITLE
Easter egg console msg

### PR DESCRIPTION
**Pull request by JavaScriptErika**
I added a fun and styled easter egg console message!! 🎉 
And I wrapped app.js code in a DOM loaded handler.

### CODE REVIEW

**Comment by BennyCarlsson** [comment]
looks great however it seems like you used some kind of auto formatter and that usually turns out in really bad merge conflicts :)

**Comment by JavaScriptErika** [comment]
@BennyCarlsson I removed the indentation (grabbed it from master)  and updated the branch with latest version of master (as of right now, lol)

**Comment by BennyCarlsson** [comment]
Great work 👍 haha yeah master updates fast here

**Comment by JavaScriptErika** [comment]
Hooray! Thank you!!

**Pull request merged**
